### ISSUE TITLE
Failed building wheel for zivid - Unknown CMake command "conan_cmake_configure"

### ISSUE THREAD

**Issue by chenxlong3** [zivid/zivid-python#225]
I tried to install zivid in a conda environment using pip but it failed building.

# Basic Information
Ubuntu 18.04
python 3.9
pip 23.0.1

# What I have done
## 1. Check openCL
```bash
clinfo -l
```
The corresponding output is
```
Platform #0: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce RTX 3090
```

## 2. Software Installation
Follow the steps in https://support.zivid.com/en/latest/getting-started/software-installation.html .
```bash
mkdir Zivid
cd Zivid

wget \
https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u18/zivid-telicam-driver_3.0.1.1-3_amd64.deb \
https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u18/zivid_2.9.0+4dbba385-1_amd64.deb \
https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u18/zivid-studio_2.9.0+4dbba385-1_amd64.deb \
https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u18/zivid-tools_2.9.0+4dbba385-1_amd64.deb

sudo apt install ./*.deb
```

## 3. Install Related Packages
```
pip install cmake ninja scikit-build
pip install "conan>=1,<2"
```

Finally,
```
pip install zivid
```
But I got this error
```
Collecting zivid
  Using cached zivid-2.9.0.2.9.0.tar.gz (68 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./anaconda3/envs/py39/lib/python3.9/site-packages (from zivid) (1.24.3)
Building wheels for collected packages: zivid
  Building wheel for zivid (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for zivid (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      cmake version 3.26.3
      
      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      CMake Warning (dev) at CMakeLists.txt:1 (project):
        cmake_minimum_required() should be called prior to this top-level project()
        call.  Please see the cmake-commands(7) manual for usage documentation of
        both commands.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/zivid-python-build-qzbwlnsv
      [1/2] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
      [2/2] Linking CXX static library liblib.a
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a/_skbuild/linux-x86_64-3.9/cmake-build
        Command:
          /tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.16 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPYTHON_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DPYTHON_LIBRARY:PATH=/root/anaconda3/envs/py39/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPython_ROOT_DIR:PATH=/root/anaconda3/envs/py39 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DPython3_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPython3_ROOT_DIR:PATH=/root/anaconda3/envs/py39 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.9.0.2.9.0 -DZIVID_SDK_VERSION=2.9.0 -DPYTHON_INTERPRETER_VERSION=3.9.16 -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
      -- Found Python3: /root/anaconda3/envs/py39/bin/python (found suitable exact version "3.9.16") found components: Interpreter Development Development.Module Development.Embed
      CMake Error at CMakeLists.txt:13 (conan_cmake_configure):
        Unknown CMake command "conan_cmake_configure".
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.16 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPYTHON_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DPYTHON_LIBRARY:PATH=/root/anaconda3/envs/py39/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPython_ROOT_DIR:PATH=/root/anaconda3/envs/py39 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DPython3_EXECUTABLE:PATH=/root/anaconda3/envs/py39/bin/python -DPython3_ROOT_DIR:PATH=/root/anaconda3/envs/py39 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/root/anaconda3/envs/py39/include/python3.9 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-a_t7ltzq/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.9.0.2.9.0 -DZIVID_SDK_VERSION=2.9.0 -DPYTHON_INTERPRETER_VERSION=3.9.16 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a
        Working directory:
          /tmp/pip-install-bri2t__d/zivid_40e05f2b37ca4c1ba33164d4774e296a/_skbuild/linux-x86_64-3.9/cmake-build
      Please see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zivid
Failed to build zivid
ERROR: Could not build wheels for zivid, which is required to install pyproject.toml-based projects
```
Sincerely hope that you could help me solve it. I have retried many times but this error always came up.

**Comment by nedrebo** [comment]
Can you try `pip install --upgrade conan==1.59.0` and then try `pip install zivid` again?

Iirc there was a breaking change in the latest 1.x release of Conan.

**Comment by chenxlong3** [comment]
> Can you try `pip install --upgrade conan==1.59.0` and then try `pip install zivid` again?
> 
> Iirc there was a breaking change in the latest 1.x release of Conan.

Thank you for the suggestion but it does not work. Still the same error.

Here is my pip list:

```
Package            Version
------------------ --------
bottle             0.12.25
certifi            2023.5.7
charset-normalizer 3.1.0
cmake              3.26.3
colorama           0.4.6
conan              1.59.0
distro             1.8.0
fasteners          0.18
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.2
ninja              1.11.1
node-semver        0.6.1
numpy              1.24.3
packaging          23.1
patch-ng           1.17.4
pip                23.0.1
pluginbase         1.0.1
Pygments           2.15.1
PyJWT              2.7.0
python-dateutil    2.8.2
PyYAML             6.0
requests           2.31.0
scikit-build       0.17.5
setuptools         67.8.0
six                1.16.0
tomli              2.0.1
tqdm               4.65.0
urllib3            1.26.16
wheel              0.38.4
```

**Comment by eskaur** [comment]
I've never really tested this with conda. Could you see if it helps to use a "normal" virtual env instead of using conda?
It should work with conda, but if it works without at least that helps narrow down the issue.

**Comment by chenxlong3** [comment]
> I've never really tested this with conda. Could you see if it helps to use a "normal" virtual env instead of using conda?
> It should work with conda, but if it works without at least that helps narrow down the issue.

I have tried to use virtualenv to create a virtual environment and install zivid. Unfortunately, the same error still occurs.

**Comment by eskaur** [comment]
We know it works with a basic 18.04 setup since that is auto-tested in the CI. Let me investigate how it differs from your setup.

**Comment by eskaur** [comment]
The CI for Ubuntu 18.04 essentially does this:

```
docker run -v $PWD:/host  -it ubuntu:18.04
cd host
./continuous-integration/linux/setup.sh
./continuous-integration/linux/build.sh
```

It works fine, but the setup is quite different from what you have. We mainly support the standard packages for each OS,
i.e. what you get if you do `apt install python3-dev python3-pip` and `pip install --upgrade pip` on that OS. 
For Ubuntu 18.04 this gives:

```
Python 3.6.9
pip 21.3.1
```

I see you are using Python 3.9, while we mainly test one the default Python of each OS.
Are either of these solutions an alternative for you?:

- Upgrade to Ubuntu 22.04 (Python 3.10)
- Stay on Ubuntu 18.04 but downgrade to the primary Python for that (Python 3.6)

**Comment by chenxlong3** [comment]
> The CI for Ubuntu 18.04 essentially does this in the repo root:
> 
> ```
> docker run -v $PWD:/host  -it ubuntu:18.04
> cd host
> ./continuous-integration/linux/setup.sh
> ./continuous-integration/linux/build.sh
> ```
> 
> It works fine, but the setup is quite different from what you have. We mainly support the standard packages for each OS, i.e. what you get if you do `apt install python3-dev python3-pip` and `pip install --upgrade pip` on that OS. For Ubuntu 18.04 this gives:
> 
> ```
> Python 3.6.9
> pip 21.3.1
> ```
> 
> I see you are using Python 3.9, while we mainly test one the default Python of each OS. Are either of these solutions an alternative for you?:
> 
> * Upgrade to Ubuntu 22.04 (Python 3.10)
> * Stay on Ubuntu 18.04 but downgrade to the primary Python for that (Python 3.6)

When I am using virtualenv, the python version and pip version are as below:
```
Python 3.6.9
pip 21.3.1 from /root/venv/lib/python3.6/site-packages/pip (python 3.6)
```
This is exactly the same as yours. But I still get this error. Would you mind providing the pip list of your successful environment?
```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from zivid) (1.19.5)
Building wheels for collected packages: zivid
  Building wheel for zivid (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/nbv/bin/python /root/nbv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpi1nuu7jf
       cwd: /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56
  Complete output (90 lines):
  cmake version 3.26.4
  
  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  CMake Warning (dev) at CMakeLists.txt:1 (project):
    cmake_minimum_required() should be called prior to this top-level project()
    call.  Please see the cmake-commands(7) manual for usage documentation of
    both commands.
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.6s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/zivid-python-build-rj6ka2zi
  [1/2] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
  [2/2] Linking CXX static library liblib.a
  
  
  --------------------------------------------------------------------------------
  -- Trying 'Ninja' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.6s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja' generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56/_skbuild/linux-x86_64-3.6/cmake-build
    Command:
      /tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/cmake/data/bin/cmake /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_VERSION_STRING:STRING=3.6.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/root/nbv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPython_EXECUTABLE:PATH=/root/nbv/bin/python -DPython_ROOT_DIR:PATH=/root/nbv -DPython_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/root/nbv/bin/python -DPython3_ROOT_DIR:PATH=/root/nbv -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.9.0.2.9.0 -DZIVID_SDK_VERSION=2.9.0 -DPYTHON_INTERPRETER_VERSION=3.6.9 -DCMAKE_BUILD_TYPE:STRING=Release
  
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
  -- Found Python3: /root/nbv/bin/python (found suitable exact version "3.6.9") found components: Interpreter Development Development.Module Development.Embed
  CMake Error at CMakeLists.txt:13 (conan_cmake_configure):
    Unknown CMake command "conan_cmake_configure".
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 639, in setup
      languages=cmake_languages,
    File "/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 333, in configure
      "An error occurred while configuring with CMake.\n"
  
  An error occurred while configuring with CMake.
    Command:
      /tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/cmake/data/bin/cmake /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_VERSION_STRING:STRING=3.6.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/root/nbv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPython_EXECUTABLE:PATH=/root/nbv/bin/python -DPython_ROOT_DIR:PATH=/root/nbv -DPython_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/root/nbv/bin/python -DPython3_ROOT_DIR:PATH=/root/nbv -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-lmx5qxj7/overlay/lib/python3.6/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.9.0.2.9.0 -DZIVID_SDK_VERSION=2.9.0 -DPYTHON_INTERPRETER_VERSION=3.6.9 -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56
    Working directory:
      /tmp/pip-install-z5858mbe/zivid_504a206b71d441edbc4ebe977dac9c56/_skbuild/linux-x86_64-3.6/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for zivid
Failed to build zivid
ERROR: Could not build wheels for zivid, which is required to install pyproject.toml-based projects
```

**Comment by nedrebo** [comment]
The CI runs on the official Ubuntu 18.04 as seen in https://github.com/zivid/zivid-python/blob/master/.github/workflows/main.yml#L122-L128

The setup is then provisioned using https://github.com/zivid/zivid-python/blob/master/continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh

You can inspect the exact environment we use in CI testing by entering an interactive docker session using the statement from `main.yml` and then running `setup.sh`. Let us know if that helps.

If you manage to reproduce the error in this environment please share the reproducer as a shell script.

**Comment by chenxlong3** [comment]
> The CI runs on the official Ubuntu 18.04 docker image as seen in https://github.com/zivid/zivid-python/blob/master/.github/workflows/main.yml#L122-L128
> 
> The setup is then provisioned using https://github.com/zivid/zivid-python/blob/master/continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
> 
> You can inspect the exact environment we use in CI testing by entering an interactive docker session using the statement from `main.yml` and then running `setup.sh`. Let us know if that helps.
> 
> If you manage to reproduce the error in this environment please share the reproducer as a shell script.

Thank you for the reply. But I am not so familiar with docker operations. I wonder if you could provide a `.whl` file as here https://github.com/zivid/zivid-python/issues/212#issuecomment-1531491461 .

**Comment by eskaur** [comment]
Sure, here's a binary whl build for the Ubuntu1804 + Python3.6 combination:
[zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt](https://github.com/zivid/zivid-python/files/11733838/zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt)

Remember to strip the ".txt" suffix before attempting installation.
Hope this works for you.

**Comment by chenxlong3** [comment]
> Sure, here's a binary whl built for the Ubuntu1804 + Python3.6 combination: [zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt](https://github.com/zivid/zivid-python/files/11733838/zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt)
> 
> Remember to strip the ".txt" suffix before attempting installation. Hope this works for you.

Thank you very much. I have successfully installed the package. Now I will close this issue.

**Comment by chenxlong3** [comment]
> Sure, here's a binary whl built for the Ubuntu1804 + Python3.6 combination: [zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt](https://github.com/zivid/zivid-python/files/11733838/zivid-2.9.0.2.9.0-cp36-cp36m-linux_x86_64.whl.txt)
> 
> Remember to strip the ".txt" suffix before attempting installation. Hope this works for you.

Thank you very much. I have successfully installed the package. Now I will close this issue.

**Comment by eskaur** [comment]
Thank you for closing. We will continue to work on making the installation process easier.
