### ISSUE TITLE
Can't install 2.6.0 python package 

### ISSUE THREAD

**Issue by domeniconappo** [zivid/zivid-python#289]
Hi there!

We are testing a not recent Zivid camera (Zivid2 M70) and apparently, it only supports 2.7 SDK.

The python package `2.6.0.2.7.0` fails to install, because the install requirements (see pyproject.toml) says it needs `conan>=2` but the conan commands that are executed are for Conan ver.1, as there is an `--installation-folder` parameter being used that is not in Conan ver 2 anymore, so the installation fails.

I see the same problem for 2.6.0.2.8.0.
This makes it impossible to install it normally, and we might need to install it from source or do some trickery to force Conan ver.1 during installation (not sure it's possible).

Would you happen to have any suggestions? :)

**Comment by johningve** [comment]
Hi!

The Zivid 2 M70 is still supported by the latest version of Zivid SDK, version 2.13.1. It only requires a firmware update, which can be done using Zivid Studio or with the `ZividFirmwareUpdater` CLI tool. Please see more detailed instructions in our knowledge base: https://support.zivid.com/en/latest/academy/camera/firmware-update.html

In case you need to use the older version, I can try to reproduce the Conan issue.

**Comment by domeniconappo** [comment]
Hi John. Thanks for the answer. 
We will try to update the firmware!

To reproduce the issue, I think it's enough to create a minimal Python project with poetry/pyproject.toml and add `zivid = "^2.6.0"` as dependency. If you try `poetry install`, the installation should fail. This is the full traceback: it's long text but if you can spot the real problem with conan command. Hope this helps.


```
  - Installing zivid (2.6.0.2.7.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  cmake version 3.30.2
  
  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  CMake Warning (dev) at CMakeLists.txt:1 (project):
    cmake_minimum_required() should be called prior to this top-level project()
    call.  Please see the cmake-commands(7) manual for usage documentation of
    both commands.
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- The CXX compiler identification is Clang 14.0.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.5s)
  -- Generating done (0.1s)
  -- Build files have been written to: /tmp/zivid-python-build-bkqok42z
  [1/2] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
  [2/2] Linking CXX static library liblib.a
  
  
  --------------------------------------------------------------------------------
  -- Trying 'Ninja' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is Clang 14.0.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is Clang 14.0.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (0.5s)
  -- Generating done (0.0s)
  -- Build files have been written to: /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja' generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-build
    Command:
      /tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.13 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/domenico/.pyenv/versions/3.10.13/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPython_ROOT_DIR:PATH=/tmp/tmpyb4gofxo/.venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DPython3_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPython3_ROOT_DIR:PATH=/tmp/tmpyb4gofxo/.venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.6.0.2.7.0 -DZIVID_SDK_VERSION=2.7.0 -DPYTHON_INTERPRETER_VERSION=3.10.13 -DCMAKE_BUILD_TYPE:STRING=Release
  
  Not searching for unused variables given on the command line.
  -- The CXX compiler identification is Clang 14.0.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
  -- Found Python3: /tmp/tmpyb4gofxo/.venv/bin/python (found suitable exact version "3.10.13") found components: Interpreter Development Development.Module Development.Embed
  -- Conan: checking conan executable
  -- Conan: Found program /tmp/tmpyb4gofxo/.venv/bin/conan
  -- Conan: Version found Conan version 2.6.0
  -- Conan executing: /tmp/tmpyb4gofxo/.venv/bin/conan install . --remote conancenter --install-folder /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-build/conan_install --settings build_type=Release --settings compiler=clang --settings compiler.version=14 --settings compiler.libcxx=libstdc++11
  usage: conan install [-h] [-v [V]] [-cc CORE_CONF] [-f FORMAT] [--name NAME]
                       [--version VERSION] [--user USER] [--channel CHANNEL]
                       [--requires REQUIRES] [--tool-requires TOOL_REQUIRES]
                       [-b BUILD] [-r REMOTE | -nr] [-u [UPDATE]] [-pr PROFILE]
                       [-pr:b PROFILE_BUILD] [-pr:h PROFILE_HOST]
                       [-pr:a PROFILE_ALL] [-o OPTIONS] [-o:b OPTIONS_BUILD]
                       [-o:h OPTIONS_HOST] [-o:a OPTIONS_ALL] [-s SETTINGS]
                       [-s:b SETTINGS_BUILD] [-s:h SETTINGS_HOST]
                       [-s:a SETTINGS_ALL] [-c CONF] [-c:b CONF_BUILD]
                       [-c:h CONF_HOST] [-c:a CONF_ALL] [-l LOCKFILE]
                       [--lockfile-partial] [--lockfile-out LOCKFILE_OUT]
                       [--lockfile-clean]
                       [--lockfile-overrides LOCKFILE_OVERRIDES] [-g GENERATOR]
                       [-of OUTPUT_FOLDER] [-d DEPLOYER]
                       [--deployer-folder DEPLOYER_FOLDER]
                       [--deployer-package DEPLOYER_PACKAGE] [--build-require]
                       [path]
  
conan install: error: unrecognized arguments: --install-folder /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-build/conan_install

  ERROR: Exiting with code: 2
  CMake Error at _skbuild/linux-x86_64-3.10/cmake-build/conan.cmake:651 (message):
    Conan install failed='2'
  Call Stack (most recent call first):
    CMakeLists.txt:24 (conan_cmake_install)
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 664, in setup
      env = cmkr.configure(
    File "/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/skbuild/cmaker.py", line 354, in configure
      raise SKBuildError(msg)
  
  An error occurred while configuring with CMake.
    Command:
      /tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.13 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/domenico/.pyenv/versions/3.10.13/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPython_ROOT_DIR:PATH=/tmp/tmpyb4gofxo/.venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DPython3_EXECUTABLE:PATH=/tmp/tmpyb4gofxo/.venv/bin/python -DPython3_ROOT_DIR:PATH=/tmp/tmpyb4gofxo/.venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/domenico/.pyenv/versions/3.10.13/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpyb4gofxo/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.6.0.2.7.0 -DZIVID_SDK_VERSION=2.7.0 -DPYTHON_INTERPRETER_VERSION=3.10.13 -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0
    Working directory:
      /tmp/tmp039uw9p3/zivid-2.6.0.2.7.0/_skbuild/linux-x86_64-3.10/cmake-build
  Please see CMake's output for more information.
  
  

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with zivid (2.6.0.2.7.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "zivid (==2.6.0.2.7.0)"'.
```

**Comment by johningve** [comment]
> To reproduce the issue, I think it's enough to create a minimal Python project with poetry/pyproject.toml and add `zivid = "^2.6.0"` as dependency. If you try `poetry install`, the installation should fail. This is the full traceback: it's long text but if you can spot the real problem with conan command. Hope this helps.

Thanks. I was able to reproduce the issue. The problem is that the older `zivid-python` packages did not constrain the conan version. To workaround the issue you must ensure that an older conan version is installed, for example `pip install "conan<2"` before installing `zivid` or add `conan<2` in your pyproject requirements.

**Comment by johningve** [comment]
In any case, I would recommend upgrading to the latest version of Zivid SDK to get the best performance and quality from your camera :)

**Comment by domeniconappo** [comment]
@johningve 
Thanks for checking! I see the problem you mentioned (I guess that when the version came out there was no conan 2 yet).
Anyway, pinning conan in project requirements wouldn't solve the issue because it's a build dependency. I also tried to pin the version in my build requirements but it's being ignored.

```toml
[build-system]
requires = ["poetry-core>=1.0.0", "conan>=1,<2"]
```

We will update the firmware of course!
Thanks again for the support.

**Comment by domeniconappo** [comment]
FYI: Our model is actually Zivid One Plus S (and not Zivid 2 M70). We could update the SDK to 2.11.1 (not the latest) and install python package 2.11.1. Everything worked! Thank you.
