### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by LucaMIMOUNI** [zivid/zivid-python#292]
Hello everyone,

I am trying to get the zivid-python in order to callibrate my zivid through this [tuto](https://support.zivid.com/en/latest/academy/applications/hand-eye/robodk-%2B-python-generate-dataset-and-perform-hand-eye-calibration.html).

However, I can't install it, neither with debien pkg or from source (Cf error below).

## Config
* Ubuntu 22.04 Jammy
* python 3.10

### To reproduce
Just a simple `pip install zivid` in your shell.
### Shell error
First error was : 
```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/luca/ros2_ws/smart_robot/src/zivid-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      cmake version 3.22.1
      
      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "/tmp/zivid-python-build-elsmxpp8/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "setup.py", line 75, in run_process
          raise RuntimeError(
      RuntimeError: Wait failed with exit code 1
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "setup.py", line 98, in _check_cpp17_compiler
          run_process(("cmake", "-GNinja", "."), cwd=temp_dir)
        File "setup.py", line 79, in run_process
          raise type(ex)("Process failed: '{}'.".format(" ".join(args))) from ex
      RuntimeError: Process failed: 'cmake -GNinja .'.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 156, in <module>
          _main()
        File "setup.py", line 122, in _main
          _check_cpp17_compiler()
        File "setup.py", line 103, in _check_cpp17_compiler
          raise RuntimeError(
      RuntimeError:
      
      +-----------------------------------------------------------+
      | !! Module setup failed !!                                 |
      |                                                           |
      | Make sure you have a working C++17 compiler installed     |
      |                                                           |
      | Refer to Readme.md for detailed installation instructions |
      +-----------------------------------------------------------+
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

So it was apriori an issue with the ninja build. So i installed it with the following command `sudo apt install ninja-build`. Now `pip install zivid` give me this shell : 

```
Defaulting to user installation because normal site-packages is not writeable
Collecting zivid
  Using cached zivid-2.13.1.2.13.1.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/luca/.local/lib/python3.10/site-packages (from zivid) (1.24.4)
Building wheels for collected packages: zivid
  Building wheel for zivid (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for zivid (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      cmake version 3.22.1
      
      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/zivid-python-build-gzuoj702
      [1/2] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
      [2/2] Linking CXX static library liblib.a
      Overriding build dir: /tmp/zivid-python-build_basa7vn_
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-2rr7ir2i/zivid_2eb240c427844ef1a173405217614361/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/zivid-python-build_basa7vn_/cmake-build
        Command:
          /tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /tmp/pip-install-2rr7ir2i/zivid_2eb240c427844ef1a173405217614361 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/zivid-python-build_basa7vn_/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.13.1.2.13.1 -DZIVID_SDK_VERSION=2.13.1 -DPYTHON_INTERPRETER_VERSION=3.10.12 -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- Downloading conan_provider.cmake from https://github.com/conan-io/cmake-conan
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at /tmp/zivid-python-build_basa7vn_/cmake-build/conan_provider.cmake:562 (find_program):
        Could not find CONAN_COMMAND using the following names: conan
      Call Stack (most recent call first):
        CMakeLists.txt:23 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 660, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 354, in configure
          raise SKBuildError(msg)
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /tmp/pip-install-2rr7ir2i/zivid_2eb240c427844ef1a173405217614361 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/zivid-python-build_basa7vn_/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cab_p6hx/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DZIVID_PYTHON_VERSION=2.13.1.2.13.1 -DZIVID_SDK_VERSION=2.13.1 -DPYTHON_INTERPRETER_VERSION=3.10.12 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-2rr7ir2i/zivid_2eb240c427844ef1a173405217614361
        Working directory:
          /tmp/zivid-python-build_basa7vn_/cmake-build
      Please see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zivid
Failed to build zivid
ERROR: Could not build wheels for zivid, which is required to install pyproject.toml-based projects
```

It seems there is a conan missing. However, I still get exact same issue after doing `pip install conan` 

Here is the shell after the pip install conan:
```
pip install conan
Defaulting to user installation because normal site-packages is not writeable
Collecting conan
  Using cached conan-2.9.2-py3-none-any.whl
Requirement already satisfied: colorama<0.5.0,>=0.4.3 in /usr/lib/python3/dist-packages (from conan) (0.4.4)
Collecting urllib3<1.27,>=1.26.6
  Using cached urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Collecting patch-ng<1.19,>=1.18.0
  Using cached patch_ng-1.18.1-py3-none-any.whl
Collecting fasteners>=0.15
  Using cached fasteners-0.19-py3-none-any.whl (18 kB)
Collecting PyYAML<7.0,>=6.0
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in /usr/lib/python3/dist-packages (from conan) (2.8.1)
Requirement already satisfied: requests<3.0.0,>=2.25 in /usr/lib/python3/dist-packages (from conan) (2.25.1)
Requirement already satisfied: Jinja2<4.0.0,>=3.0 in /usr/lib/python3/dist-packages (from conan) (3.0.3)
Requirement already satisfied: distro<=1.8.0,>=1.4.0 in /usr/lib/python3/dist-packages (from conan) (1.7.0)
Installing collected packages: urllib3, PyYAML, patch-ng, fasteners, conan
Successfully installed PyYAML-6.0.2 conan-2.9.2 fasteners-0.19 patch-ng-1.18.1 urllib3-1.26.20
```

It seems like this post #225 talks about the same issue. However, the solution was to give a personalized binary pkg to install for ubuntu 18.04 + python 3.6 which is not my config.
 
I do not know, neither understand what is wrong here, getting a little of help on this would be much appreciated ! 

Ty.

**Comment by johningve** [comment]
Hi Luca!

Are you using the latest version of pip? We have sometimes seen issues with older pip versions. I just tested in a clean docker container of Ubuntu 22.04 and after upgrading pip I can run `pip install zivid` even without having CMake or Ninja installed (these should be sourced automatically by pip).

**Comment by LucaMIMOUNI** [comment]
Thank you for your reactivity, it seems that it was the culprit ! With pip updated to latest version (i.e 24.3.1), `pip install zivid` give me now
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: zivid in /home/luca/.local/lib/python3.10/site-packages (2.13.1.2.13.1)
Requirement already satisfied: numpy in /home/luca/.local/lib/python3.10/site-packages (from zivid) (1.24.4)
```

So everything seems to be good !

Thank you a lot !
