### ISSUE TITLE
issues to install zivid python with SDK 1.7.0 in a Docker container

### ISSUE THREAD

**Issue by pbermell** [zivid/zivid-python#40]
Hello,
I successfully built few months ago a docker container to run the Zivid camera in a multi-system setup managed by a message broker (mqtt). However, when I tried to update my container image to SDK 1.7.0 I get building problems. Any insights? The errors I get when I try to pip3 install zivid are listed here: 

```
root@533705a88a69:/# pip3 install zivid
Collecting zivid
  Downloading https://files.pythonhosted.org/packages/c2/27/fa4b9148adc3d93639a9949e6dd6992e009f872b6b31e6c220b11cdd79fa/zivid-0.9.2.1.7.0.tar.gz
Collecting numpy (from zivid)
  Downloading https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl (20.0MB)
    100% |################################| 20.0MB 93kB/s 
Building wheels for collected packages: zivid
  Running setup.py bdist_wheel for zivid ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ld0poabm/zivid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0744q630pip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.4.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-build-ld0poabm/zivid/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  -- The CXX compiler identification is GNU 7.4.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
  -- Conan: Automatic detection of conan settings from cmake
  -- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=7;-s;compiler.libcxx=libstdc++11
  -- Conan executing: conan install . -s build_type=Release -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++11 -g=cmake
  CMake Error at _skbuild/linux-x86_64-3.6/cmake-build/conan.cmake:399 (message):
    Conan install failed='No such file or directory'
  Call Stack (most recent call first):
    _skbuild/linux-x86_64-3.6/cmake-build/conan.cmake:485 (conan_cmake_install)
    CMakeLists.txt:12 (conan_cmake_run)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/skbuild/setuptools_wrap.py", line 574, in setup
      languages=cmake_languages
    File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 232, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  
  An error occurred while configuring with CMake.
    Command:
      "cmake" "/tmp/pip-build-ld0poabm/zivid" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3" "-DPYTHON_VERSION_STRING:STRING=3.6.9" "-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m" "-DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.6/dist-packages/skbuild/resources/cmake" "-DZIVID_PYTHON_VERSION=0.9.2.1.7.0" "-DZIVID_SDK_VERSION=1.7.0" "-DCMAKE_BUILD_TYPE:STRING=Release"
    Source directory:
      /tmp/pip-build-ld0poabm/zivid
    Working directory:
      /tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-build
  Please see CMake's output for more information.
  
  ----------------------------------------
  Failed building wheel for zivid
  Running setup.py clean for zivid
Failed to build zivid
Installing collected packages: numpy, zivid
  Running setup.py install for zivid ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ld0poabm/zivid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-garujadt-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-ld0poabm/zivid/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
    -- Conan: Automatic detection of conan settings from cmake
    -- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=7;-s;compiler.libcxx=libstdc++11
    -- Conan executing: conan install . -s build_type=Release -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++11 -g=cmake
    CMake Error at _skbuild/linux-x86_64-3.6/cmake-build/conan.cmake:399 (message):
      Conan install failed='No such file or directory'
    Call Stack (most recent call first):
      _skbuild/linux-x86_64-3.6/cmake-build/conan.cmake:485 (conan_cmake_install)
      CMakeLists.txt:12 (conan_cmake_run)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/skbuild/setuptools_wrap.py", line 574, in setup
        languages=cmake_languages
      File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 232, in configure
        os.path.abspath(CMAKE_BUILD_DIR())))
    
    An error occurred while configuring with CMake.
      Command:
        "cmake" "/tmp/pip-build-ld0poabm/zivid" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3" "-DPYTHON_VERSION_STRING:STRING=3.6.9" "-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m" "-DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.6/dist-packages/skbuild/resources/cmake" "-DZIVID_PYTHON_VERSION=0.9.2.1.7.0" "-DZIVID_SDK_VERSION=1.7.0" "-DCMAKE_BUILD_TYPE:STRING=Release"
      Source directory:
        /tmp/pip-build-ld0poabm/zivid
      Working directory:
        /tmp/pip-build-ld0poabm/zivid/_skbuild/linux-x86_64-3.6/cmake-build
    Please see CMake's output for more information.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ld0poabm/zivid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-garujadt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ld0poabm/zivid/

```
I have attached here both the old dockerfile (dockerfile_zivid_old) which worked perfectly for 1.4.0
and the new dockerfile (dockerfile_zivid) which produces the errors when running `pip3 install zivid`

OLD docker file with 1.4.0 (works) 

```
FROM  nvidia/opencl:runtime-ubuntu18.04

CMD cd home
CMD pwd
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get update
CMD ls
RUN apt-get install -y udev
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.4.0+956f554d-12/u18/telicam-sdk_2.0.0.1-1_amd64.deb
RUN dpkg -i telicam-sdk_2.0.0.1-1_amd64.deb
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.4.0+956f554d-12/u18/zivid_1.4.0+956f554d-12_amd64.deb
RUN dpkg -i zivid_1.4.0+956f554d-12_amd64.deb
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.4.0+956f554d-12/u18/zivid-tools_1.4.0+956f554d-12_amd64.deb
RUN dpkg -i zivid-tools_1.4.0+956f554d-12_amd64.deb
RUN pip3 install scikit-build cmake ninja
RUN pip3 install zivid
RUN pip3 install paho-mqtt
RUN apt-get install -y mosquitto-clients
```

NEW docker file with 1.7.0 (does not work) 
```
FROM  nvidia/opencl:runtime-ubuntu18.04

CMD cd home
CMD pwd
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get update
CMD ls
RUN apt-get install -y udev
RUN wget https://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid-telicam-driver_2.0.0.1-1_amd64.deb
RUN dpkg -i zivid-telicam-driver_2.0.0.1-1_amd64.deb
RUN wget https://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid_1.7.0+a115eaa4-4_amd64.deb
RUN dpkg -i zivid_1.7.0+a115eaa4-4_amd64.deb
RUN wget https://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid-tools_1.7.0+a115eaa4-4_amd64.deb
RUN dpkg -i zivid-tools_1.7.0+a115eaa4-4_amd64.deb
RUN apt-get update -y
RUN apt-get upgrade -y 
RUN pip3 install scikit-build cmake ninja
#RUN pip3 install zivid
#RUN pip3 install paho-mqtt
#RUN apt-get install -y mosquitto-clients
#RUN apt-get update
```

I use the docker NVIDIA runtime to run the container and this is my docker version details:

```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:40:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by eskaur** [comment]
Thank you for a thorough report. I'll look into this now.

**Comment by nedrebo** [comment]
I think this line needs to be updated: `RUN pip3 install scikit-build cmake ninja` with the added content in `pyproject.toml`.

However, if you upgrade pip before doing `RUN pip3 install zivid` then you should not need to do the above at all because newer versions of pip supports `pyproject.toml`.

**Comment by eskaur** [comment]
Unfortunately, `pip3 install --upgrade pip` seems to break the pip-installation on this docker image.
https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main

**Comment by pbermell** [comment]
certainly does....

```
root@a62514d97e60:/# pip3 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 1.3MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-19.3.1
root@a62514d97e60:/# pip3 install zivid
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

**Comment by eskaur** [comment]
For now you can get away with
```
RUN pip3 install scikit-build
RUN pip3 install cmake
RUN pip3 install ninja
RUN pip3 install zivid
```
but that doesn't solve your original problem...

**Comment by eskaur** [comment]
Add a `pip3 install conan` and it should work.

**Comment by eskaur** [comment]
The following Docker image builds fine on my computer:

```
FROM nvidia/opencl:runtime-ubuntu18.04

WORKDIR /workdir

# Setting up environment
RUN apt update
RUN apt upgrade --assume-yes
RUN apt install python3 --assume-yes
RUN apt install python3-pip --assume-yes

# Install Zivid SDK
RUN apt install wget --assume-yes
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid-telicam-driver_2.0.0.1-1_amd64.deb
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid_1.7.0+a115eaa4-4_amd64.deb
RUN wget http://www.zivid.com/hubfs/softwarefiles/releases/1.7.0+a115eaa4-4/u18/zivid-tools_1.7.0+a115eaa4-4_amd64.deb
RUN apt-get install ./zivid* --assume-yes

# Install zivid-python
RUN pip3 install scikit-build
RUN pip3 install cmake
RUN pip3 install ninja
RUN pip3 install conan
RUN pip3 install zivid
```

**Comment by eskaur** [comment]
Run with 
```
docker run --device /dev/bus/usb:/dev/bus/usb --runtime=nvidia -ti you-image-here
```
to get access to the camera and GPU.

**Comment by pbermell** [comment]
Thanks @eskaur 
builds beautifully now on 1.7.0!

I'd like at some point to build the CPP samples as well but that seems to be quite a creature (PCD.. OpenCV... Eigen...). Theoretically with those built into a running container I could use the buil CPP scripts...
have you guys been looking in that direction? 

thanks anyway

**Comment by eskaur** [comment]
Not completely sure I understand what you are saying. Are you proposing that we should ship Docker images with a ready-to-go environment to build our samples?

**Comment by nedrebo** [comment]
@knatten FYI, feedback about cpp-extra-samples

We are working on making those samples easier to build with all 3rd party libs enabled.

**Comment by pbermell** [comment]
Yes. I think this is what I meant.......
With this approach, you freeze a configuration (image) that works for the device and the specific sdk. It also has all the dependencies in place. 
For me as a user, I just build and run the container with everything on board. Or I add my bits to the dockerfile, (i.e. a message broker client). 
In my particular case I mount my scripts folder in the running container and I run the scripts I have in my host computer. 

On this extract of my `docker-compose.yml` I start the container and run `bash -c "python3 /home/RGB_extract.py"` This script starts a listener that waits for messages instructing the Zivid to make a shot. Those messages are sent by a robot arm.


```
  zivid-camera:
    build:
      context: .
      dockerfile: dockerfile_zivid
    image: pbg/zivid:release
    runtime: nvidia--
    user: root
    hostname: zividcamera
    depends_on:
      - mosquitto
    privileged: true
    volumes:
      - ./:/home
    command: bash -c "python3 /home/timedshot.py"
    networks:
      - backend
    expose:
      - 1883
      - 8080
    restart: always

```

In the case of the CPP samples, I can see the usefulness of having a working image (dockerfile) to do some  something similar but with the more functional CPP scripts. In this case, you launch the image get a message and based on this run some of the CPP build scripts inside the running contianer.

I think that in general having tested dockerimage files ready for users will improve usability and adoption of Zivid... but I may be too biased by my use cases...

thanks

**Comment by nedrebo** [comment]
We use docker internally and for the CI in most of our repositories. You can see an example here:
https://github.com/zivid/zivid-python/blob/8908c1906916c5c7e331aed9efacf064dc854509/azure-pipelines.yml#L44-L49

As you can see we call a `setup.sh` script. The reason for not having a dockerfile it that this script can also be used on bare bone machines.

Those `setup.sh` scripts are guaranteed to be up to date and woking since they are used in the CI. If possible you can try to base your dockerfiles on `setup.sh` instead of manually hardcoding all the commands.

**Comment by pbermell** [comment]
Thanks for sharing @nedrebo & @eskaur !
I will have a look into all that when I have a bit of time to spare.

**Comment by eskaur** [comment]
\
